elasticsearch: &es
  turn_on: False
  hosts: [ 'https://b5cec84eb1b142c593a5e487a5094c7e.us-central1.gcp.cloud.es.io:443' ]
  api_key: b'gAAAAABlxR5RDF5LpTrFZpHtzOGn17RZV223jOiLq5a-Qse2Kr0A2PbGwRSExA4ZkrM5gOc3Oo9N6Q39UAkdrdcPFO_SMn1PtQl0W9x8VaabDVmxcrIvyny5xADzK9uQtUM9Gk0uNeajQEc5ahA9mbHpI3nmytBxIg=='
log_setting: &log
  level: INFO
  console_out: False
countries: # same as project directory name
  QA1:
    # https://restcountries.com/#api-endpoints-using-this-project
    countries_api:
      host: https://restcountries.com/v3.1/
    log_setting:
      <<: *log
    elasticsearch:
      <<: *es
  QA2:
    # https://restcountries.com/#api-endpoints-using-this-project
    countries_api:
      host: https://restcountries.com/v3.1/
    log_setting:
      <<: *log
    elasticsearch:
      <<: *es
dvdrental: # same as project directory name
  QA1:
    dvdrental_db:
      db_name: dvdrental
      host: localhost
      username: postgres
      password: b'gAAAAABlxTDzfnALIK1xc2vYIbUMPlkSUrHhbJ70kHm7RMsLwzSESjSfGqDYykTWHGvZEEgiTdXX7MeWUbxLmKqMqusRDRBF9Q=='
    log_setting:
      <<: *log
    elasticsearch:
      <<: *es