elasticsearch: &es
  turn_on: False
  hosts: [ 'replace_me_with_elasticsearch_host_url' ] ## replace with hostname from 'ElasticSearch basic setup' step # 10  in README.md
  api_key: 'replace_me_with_encrypted_api_key' ## replace with apikey from 'ElasticSearch basic setup' step #4 in README.md
log_setting: &log
  level: INFO
  console_out: False
countries: # same as project directory name
  QA1:
    # https://restcountries.com/#api-endpoints-using-this-project
    countries_api:
      host: https://restcountries.com/v3.1/
    log_setting:
      <<: *log
    elasticsearch:
      <<: *es
  QA2:
    # https://restcountries.com/#api-endpoints-using-this-project
    countries_api:
      host: https://restcountries.com/v3.1/
    log_setting:
      <<: *log
    elasticsearch:
      <<: *es
dvdrental: # same as project directory name
  QA1:
    dvdrental_db:
      db_name: dvdrental
      host: localhost
      username: 'replace_me_with_db_username' ## From step 4 in README.md 'Connecting to PostgreSQL database server' section
      password: 'replace_me_with_encrypted_database_password' ## From step 4 in README.md 'Connecting to PostgreSQL database server' section
    log_setting:
      <<: *log
    elasticsearch:
      <<: *es